name: flutter_scripts
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
dependencies: {args: ^2.3.1, package_info_plus: ^1.4.2, process_run: ^0.12.3+2}
